// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sql "project-name/app/models/sql"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryUserDT is an autogenerated mock type for the RepositoryUserDT type
type RepositoryUserDT struct {
	mock.Mock
}

// FindByGCN provides a mock function with given fields: in
func (_m *RepositoryUserDT) FindByGCN(in string) (sql.UserDT, error) {
	ret := _m.Called(in)

	var r0 sql.UserDT
	if rf, ok := ret.Get(0).(func(string) sql.UserDT); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(sql.UserDT)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
