// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sql "project-name/app/models/sql"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryMBOnBoarding is an autogenerated mock type for the RepositoryMBOnBoarding type
type RepositoryMBOnBoarding struct {
	mock.Mock
}

// FindByNIK provides a mock function with given fields: in
func (_m *RepositoryMBOnBoarding) FindByNIK(in string) (sql.MBOnboarding, error) {
	ret := _m.Called(in)

	var r0 sql.MBOnboarding
	if rf, ok := ret.Get(0).(func(string) sql.MBOnboarding); ok {
		r0 = rf(in)
	} else {
		r0 = ret.Get(0).(sql.MBOnboarding)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
