// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sql "project-name/app/models/sql"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryBiller is an autogenerated mock type for the RepositoryBiller type
type RepositoryBiller struct {
	mock.Mock
}

// Read provides a mock function with given fields: in
func (_m *RepositoryBiller) Read(in int) ([]sql.Biller, error) {
	ret := _m.Called(in)

	var r0 []sql.Biller
	if rf, ok := ret.Get(0).(func(int) []sql.Biller); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sql.Biller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
